INSERT INTO client (id,
authorization_grant_types,
client_authentication_methods,
client_id,
client_id_issued_at,
client_name,
client_secret,
client_secret_expires_at,
client_settings,
redirect_uris,
scopes,
token_settings) VALUES
	 ('abbc70f1-fb59-4b42-b1e4-c52fa0080bea',
     'refresh_token,client_credentials,authorization_code,custom_password,password',
     'client_secret_basic,client_secret_post',
     'cripto-app',
     now(),
     'cripto-app',
     '$2a$08$.9jp29ZQJS1MA2XcNiTMOexQVT.18gNmVAmMRsJ7tAjSR03AINWOa',
     '2030-12-31 00:00:00',
     '{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":false,"settings.client.require-authorization-consent":true}',
     'http://localhost:8083/integracao/callback',
     'read,write,profile,introspection',
     '{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":true,"settings.token.id-token-signature-algorithm":["org.springframework.security.oauth2.jose.jws.SignatureAlgorithm","RS256"],"settings.token.access-token-time-to-live":["java.time.Duration",86400.000000000],"settings.token.access-token-format":{"@class":"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat","value":"self-contained"},"settings.token.refresh-token-time-to-live":["java.time.Duration",100000.000000000],"settings.token.authorization-code-time-to-live":["java.time.Duration",86400.000000000]}');